apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: STORAGE_SERVICE_HOST
              valueFrom:
                secretKeyRef:
                  name: snapix-back-storage-production-config-secret
                  key: STORAGE_SERVICE_HOST
            - name: STORAGE_SERVICE_PORT
              valueFrom:
                secretKeyRef:
                  name: snapix-back-storage-production-config-secret
                  key: STORAGE_SERVICE_PORT
            - name: STORAGE_SERVICE_MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: snapix-back-storage-production-config-secret
                  key: STORAGE_SERVICE_MONGO_DB