name: Main Gateway Test & Lint

on:
  push:
    branches:
      - release/**


jobs:
  tests-unit:
    name: Unit Tests All
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma
        run: yarn main:prisma:generate

      - name: Test main
        run: yarn test:main

      - name: Test notifier
        run: yarn test:notifier

      - name: Test storage
        run: yarn test:storage

      - name: Test payments
        run: yarn test:payments

  tests-e2e:
    name: E2E Tests All
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
#    needs: tests-unit
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma
        run: yarn main:prisma:generate

      - name: Test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ACCESS_TOKEN_SECRET_EXPIRES_IN: ${{ secrets.ACCESS_TOKEN_SECRET_EXPIRES_IN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET_EXPIRES_IN: ${{ secrets.REFRESH_TOKEN_SECRET_EXPIRES_IN }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          RMQ_URLS: ${{ secrets.RMQ_URLS }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}
        run: yarn test:main:e2e

  tsc:
    name: Typescript Check
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma
        run: yarn main:prisma:generate

      - name: TSC All
        run: yarn tsc

  lint:
    name: Lint
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
#    needs: tsc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Lint main
        run: yarn lint:main:check

      - name: Lint libs
        run: yarn lint:libs:check

      - name: Lint notifier
        run: yarn lint:notifier:check
